// <auto-generated />
using System;
using KulupYonetimi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KulupYonetimi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251201191758_Baseline")]
    partial class Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KulupYonetimi.Models.Entities.Degerlendirme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EtkinlikId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Yorum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EtkinlikId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Degerlendirmeler");
                });

            modelBuilder.Entity("KulupYonetimi.Models.Entities.Duyuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("GecerlilikBitis")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("KulupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YayinTarihi")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("KulupId");

                    b.ToTable("Duyurular");
                });

            modelBuilder.Entity("KulupYonetimi.Models.Entities.Etkinlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("KulupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("KulupId");

                    b.ToTable("Etkinlikler");
                });

            modelBuilder.Entity("KulupYonetimi.Models.Entities.EtkinlikKayit", b =>
                {
                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("EtkinlikId")
                        .HasColumnType("int");

                    b.HasKey("KullaniciId", "EtkinlikId");

                    b.HasIndex("EtkinlikId");

                    b.ToTable("EtkinlikKayitlari");
                });

            modelBuilder.Entity("KulupYonetimi.Models.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("KulupYonetimi.Models.Entities.KullaniciKulup", b =>
                {
                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("KulupId")
                        .HasColumnType("int");

                    b.HasKey("KullaniciId", "KulupId");

                    b.HasIndex("KulupId");

                    b.ToTable("KullaniciKulupler");
                });

            modelBuilder.Entity("KulupYonetimi.Models.Entities.Kulup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("YoneticiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YoneticiId");

                    b.ToTable("Kulupler");
                });

            modelBuilder.Entity("KulupYonetimi.Models.Entities.Degerlendirme", b =>
                {
                    b.HasOne("KulupYonetimi.Models.Entities.Etkinlik", "Etkinlik")
                        .WithMany("Degerlendirmeler")
                        .HasForeignKey("EtkinlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KulupYonetimi.Models.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etkinlik");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KulupYonetimi.Models.Entities.Duyuru", b =>
                {
                    b.HasOne("KulupYonetimi.Models.Entities.Kulup", "Kulup")
                        .WithMany("Duyurular")
                        .HasForeignKey("KulupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kulup");
                });

            modelBuilder.Entity("KulupYonetimi.Models.Entities.Etkinlik", b =>
                {
                    b.HasOne("KulupYonetimi.Models.Entities.Kulup", "Kulup")
                        .WithMany("Etkinlikler")
                        .HasForeignKey("KulupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kulup");
                });

            modelBuilder.Entity("KulupYonetimi.Models.Entities.EtkinlikKayit", b =>
                {
                    b.HasOne("KulupYonetimi.Models.Entities.Etkinlik", "Etkinlik")
                        .WithMany("Kayitlar")
                        .HasForeignKey("EtkinlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KulupYonetimi.Models.Entities.Kullanici", "Kullanici")
                        .WithMany("KayitliEtkinlikler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etkinlik");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KulupYonetimi.Models.Entities.KullaniciKulup", b =>
                {
                    b.HasOne("KulupYonetimi.Models.Entities.Kullanici", "Kullanici")
                        .WithMany("UyeOlunanKulupler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KulupYonetimi.Models.Entities.Kulup", "Kulup")
                        .WithMany("Uyeler")
                        .HasForeignKey("KulupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Kulup");
                });

            modelBuilder.Entity("KulupYonetimi.Models.Entities.Kulup", b =>
                {
                    b.HasOne("KulupYonetimi.Models.Entities.Kullanici", "Yonetici")
                        .WithMany("YonetilenKulupler")
                        .HasForeignKey("YoneticiId");

                    b.Navigation("Yonetici");
                });

            modelBuilder.Entity("KulupYonetimi.Models.Entities.Etkinlik", b =>
                {
                    b.Navigation("Degerlendirmeler");

                    b.Navigation("Kayitlar");
                });

            modelBuilder.Entity("KulupYonetimi.Models.Entities.Kullanici", b =>
                {
                    b.Navigation("KayitliEtkinlikler");

                    b.Navigation("UyeOlunanKulupler");

                    b.Navigation("YonetilenKulupler");
                });

            modelBuilder.Entity("KulupYonetimi.Models.Entities.Kulup", b =>
                {
                    b.Navigation("Duyurular");

                    b.Navigation("Etkinlikler");

                    b.Navigation("Uyeler");
                });
#pragma warning restore 612, 618
        }
    }
}
